'use client'
import { ReactNode } from 'react'
// import './globals.css'
import StyledComponentsRegistry from '@/lib/styled-components-registry';
import { ThemeProvider } from 'styled-components'

import GlobalStyles from '@/styles/global';
import theme from '@/styles/theme';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <StyledComponentsRegistry>
      <ThemeProvider theme={theme}>
        <html lang="en">
          <GlobalStyles />
          <body>{children}</body>
        </html>
      </ThemeProvider>
    </StyledComponentsRegistry>
  )
}
